# Global configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Entry points configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  
  websecure:
    address: ":443"

# Providers configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  
  file:
    directory: "/etc/traefik/config"
    watch: true

# API configuration
api:
  insecure: false

# Let's Encrypt configuration
certificatesResolvers:
  myresolver:
    acme:
      email: "vua.okafor@gmail.com"
      storage: "/etc/traefik/acme/acme.json"
      tlsChallenge: true

# Log configuration
log:
  level: "INFO"